### ISSUE TITLE
Migrate the hugo site to docusaurus

### ISSUE THREAD

**Issue by willingc** [nteract/user-guide#12]
I did some research last night and one key feature that docusaurus has over hugo is the ability to version documentation in a straightforward manner.

Between that and docusaurus has a more familiar workflow (js/react), I think it will be easier to maintain docs. Going to begin the migration :smile:

**Comment by rgbkrk** [comment]
Oh hey that's great!!!

I'm really happy if we're able to use our react components in here!

**Comment by willingc** [comment]
I've got it mostly ported on my machine already 👍
